services:
  app:
    image: picpay_simplificado:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: picpay_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/picpay-simplificado
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234567
    depends_on:
      - database

  database:
    image: postgres:15-alpine
    container_name: picpay_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: picpay-simplificado
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
